version: 2

sources:
  - name: tpch_sf1
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
    tables:
      - name: customer
        description: "Customer master data from Snowflake TPCH sample dataset"
        columns:
          - name: c_custkey
            description: "Primary key"
            tests:
              - not_null
              - unique
          - name: c_nationkey
            description: "FK to nation"
            tests:
              - not_null

models:
  - name: stg_customer
    description: '{{ doc("cust_nation") }}'
    columns:
      - name: c_custkey
        description: "Unique identifier for each customer"
        tests:
          - not_null
          - unique
      - name: c_name
        description: "Customer full name"
      - name: c_nationkey
        description: "Reference to nation dimension"
      - name: c_acctbal
        description: "Customers account balance"
      - name: c_mktsegment
        description: "Market segment classification of the customer"

  - name: Stg_nation_customer
    description: "{{ doc('cust_nation') }}"
    columns:
      - name: c_custkey
        description: "Unique identifier for each customer derived from stg_customer model"
        tests:
          - not_null
          - unique
      - name: c_name
        description: "Customer full name"
      - name: c_nationkey
        description: "Reference to nation dimension"
      - name: n_name
        description: "Nation name for associated customers derived from stg_nation model"
      - name: c_acctbal
        description: "Customers account balance"
      - name: c_mktsegment
        description: "Market segment classification of the customer"

  - name: stg_nation
    description: "This is for nation model"
    columns:
      - name: n_nationkey
        description: "Unique identifier for each nation derived from stg_nation"
        tests:
          - not_null
          - unique
      - name: n_name
        description: "Country name"
